# Generated by Django 5.1.4 on 2025-08-05 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Item', '0001_initial'),
        ('Personagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('equipado', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.item')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='Personagem.personagem')),
            ],
            options={
                'db_table': 'Inventario_inventarios',
                'permissions': [('detail_inventario', 'Pode ver o detalhe de inventario')],
            },
        ),
    ]
