# Generated by Django 5.1.4 on 2025-08-06 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Personagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='Personagem.personagem'),
        ),
    ]
