# Generated by Django 5.1.4 on 2025-08-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Evento_eventos',
                'permissions': [('detail_eventos', 'Pode ver o detalhe do evento')],
            },
        ),
    ]
