# Generated by Django 5.1.4 on 2025-06-26 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guilda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('guilda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guilda.guilda')),
            ],
            options={
                'db_table': 'Jogador_jogadores',
                'permissions': [('detail_setor', 'Pode ver o detalhe de setor')],
            },
        ),
    ]
