# Generated by Django 4.2.21 on 2025-07-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jogador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'permissions': [('detail_jogador', 'Pode ver o detalhe de jogador')]},
        ),
    ]
