# Generated by Django 5.1.4 on 2025-08-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jogador', '0002_alter_jogador_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='guilda',
        ),
    ]
