# Generated by Django 5.1.4 on 2025-08-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guilda', '0001_initial'),
        ('Jogador', '0003_remove_jogador_guilda'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='guilda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='Guilda.guilda'),
        ),
    ]
