# Generated by Django 5.1.4 on 2025-08-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'item_itens',
                'permissions': [('detail_item', 'Pode ver o detalhe do item')],
            },
        ),
    ]
