# Generated by Django 4.2.21 on 2025-07-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'item_itens',
                'permissions': [('detail_item', 'Pode ver o detalhe do item')],
            },
        ),
    ]
