# Generated by Django 4.2.21 on 2025-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
