# Generated by Django 5.1.4 on 2025-08-06 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guilda', '0001_initial'),
        ('Personagem', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='guilda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='Guilda.guilda'),
        ),
    ]
