# Generated by Django 4.2.21 on 2025-07-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'npc_npcs',
                'permissions': [('detail_npc', 'Pode ver o detalhe do npc')],
            },
        ),
    ]
