# Generated by Django 4.2.21 on 2025-08-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
