# Generated by Django 5.1.4 on 2025-08-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0002_alter_npc_descricao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='npc',
            table='Npc_npcs',
        ),
    ]
