# Generated by Django 5.1.4 on 2025-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monstro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('raca', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Monstro_Monstros',
                'permissions': [('detail_Monstro', 'Pode ver o detalhe de Monstro')],
            },
        ),
    ]
