# Generated by Django 5.1.4 on 2025-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('nivel_minimo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Dungeon_dungeons',
                'permissions': [('detail_dungeon', 'Pode ver o detalhe de dungeon')],
            },
        ),
    ]
