# Generated by Django 5.1.4 on 2025-08-05 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('recompensa', models.CharField(max_length=100)),
                ('concluida', models.BooleanField(default=False)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personagem.personagem')),
            ],
            options={
                'db_table': 'missao_missoes',
                'permissions': [('detail_missao', 'Pode ver o detalhe da missao')],
            },
        ),
    ]
