# Generated by Django 5.1.4 on 2025-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guilda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Guilda_guildas',
                'permissions': [('detail_guilda', 'Pode ver o detalhe da guilda')],
            },
        ),
    ]
