# Generated by Django 5.1.4 on 2025-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Efeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('duracao', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'Efeito_efeitos',
                'permissions': [('detail_efeitos', 'Pode ver o detalhe de efeito')],
            },
        ),
    ]
